---
- name: Check if kubeadm exists
  become: true
  ansible.builtin.stat:
    path: /usr/bin/kubeadm
  register: kubeadm_binary

- name: Reset the cluster state if kubeadm is present
  become: true
  ansible.builtin.command: kubeadm reset -f
  when: kubeadm_binary.stat.exists
  ignore_errors: true

- name: Stop related services
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  loop:
    - kubelet
    - containerd
  ignore_errors: true

- name: Remove CNI configuration files
  become: true
  ansible.builtin.file:
    path: /etc/cni/net.d/
    state: absent

- name: Remove Kubernetes configuration directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/kubernetes
    - /var/lib/kubelet
    - /var/lib/etcd

- name: Clean up user kubeconfig
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: absent

- name: Reload systemd daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: yes
