---
# Tasks for worker nodes

- name: Perform network cleanup
  ansible.builtin.include_tasks: network-cleanup.yml

- name: Delete old node object from cluster (if exists)
  become: true
  ansible.builtin.command: "kubectl delete node {{ ansible_hostname }}"
  delegate_to: "{{ groups['master_nodes'][0] }}"
  register: delete_node_result
  failed_when:
    - delete_node_result.rc != 0
    - "'NotFound' not in delete_node_result.stderr"
  changed_when: delete_node_result.rc == 0
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Reset worker node to a clean state
  become: true
  ansible.builtin.command: kubeadm reset -f
  ignore_errors: true

- name: Ensure containerd and kubelet services are started
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - containerd
    - kubelet

- name: Fetch join command from master
  ansible.builtin.slurp:
    src: /tmp/kubeadm_join_command.sh
  register: join_command_slurp
  delegate_to: "{{ groups['master_nodes'][0] }}"

- name: Join the worker node to the cluster
  become: true
  ansible.builtin.command: "{{ join_command_slurp.content | b64decode | trim }}"
