---
# infrastructure/ansible/roles/install_jenkins_controller/tasks/configure-jcasc.yml

- name: Create docker-compose.yml from template
  template:
    src: docker-compose.yml.j2
    dest: "{{ jenkins_home_on_host }}/docker-compose.yml"
    owner: '1000'
    group: '1000'
    mode: '0644'
  notify: restart jenkins

- name: Create Jenkins JCasC config file in root of JENKINS_HOME
  template:
    src: jenkins.yaml.j2
    dest: "{{ jenkins_home_on_host }}/jenkins.yaml"
    owner: '1000'
    group: '1000'
    mode: '0644'
  notify: restart jenkins
