galaxy_info:
  author: Gemini
  description: Installs a Kubernetes cluster using kubeadm.
  company: Google

  license: Apache-2.0

  min_ansible_version: "2.9"

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy

  galaxy_tags:
    - kubernetes
    - cluster
    - kubeadm
    - containerd

dependencies: []