{{- range .Values.topics }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .name }}
  labels:
    strimzi.io/cluster: {{ $.Release.Name }}-kafka
spec:
  partitions: {{ .partitions | default 1 }}
  replicas: {{ .replicas | default 1 }}
  config:
    retention.ms: {{ .retentionMs | default 604800000 }}
{{- end }}
