---
kafka__download_url: https://archive.apache.org/dist/kafka/{{ kafka_version }}/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz
kafka__download_destination: "{{ kafka_download_directory }}/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz"
kafka__dependencies: "{{ (ansible_os_family == 'Debian') | ternary(['openjdk-' ~ kafka_java_version ~ '-jre-headless'], 'java-' ~ kafka_java_version ~ '-openjdk-headless') }}"
kafka__default_listeners: "{{ ('controller' in kafka_node_roles) | ternary(('broker' in kafka_node_roles) | ternary(['PLAINTEXT://:9092', 'CONTROLLER://:9093'], ['CONTROLLER://:9093']), ['PLAINTEXT://:9092']) }}"
kafka__listeners: "{{ (kafka_listeners | length > 0) | ternary(kafka_listeners, kafka__default_listeners) }}"
kafka__uuid_file: "{{ kafka_home }}/CLUSTER_UUID.lock"
kafka__config_path: "{{ kafka_config_path | default(kafka_home ~ '/server.properties') }}"
kafka__opts: "{{ (kafka_opts | type_debug == 'list') | ternary(kafka_opts | join(' '), kafka_opts) }}"