all:
  vars:
    # Connection settings
    # @system: VM Arch Linux
    # ansible_user: zh
    # ansible_ssh_private_key_file: ~/.ssh/vm-arch_zh
    # @system: VM Ubuntu 22.04
    ansible_user: pop_zh
    ansible_ssh_private_key_file: ~/.ssh/vm-pop_zh
    ansible_python_interpreter: /usr/bin/python3
    ansible_become_pass: " "
  children:
    
    # KUBERNETES CLUSTER
    master_nodes:
      vars:
        # @system: VM Arch Linux
        ansible_user: zh
        ansible_ssh_private_key_file: ~/.ssh/vm-arch_zh
      hosts:
        master-node-01:
          ansible_host: 192.168.0.113
    # worker_nodes:
    # single_hosts:

    # # KAFKA
    # kafka_nodes:
    #   vars:
    #     # @system: VM Ubuntu 22.04
    #     # @upd: group_vars/kafka_nodes/main.yml
    #     kafka_install_dependencies: true
    #   hosts:
    #     kafka-node-01:
    #       ansible_host: 192.168.0.191
    #       kafka_node_id: 1
    #       kafka_node_roles: ['broker', 'controller']
    #     kafka-node-02:
    #       ansible_host: 192.168.0.192
    #       kafka_node_id: 2
    #       kafka_node_roles: ['broker', 'controller']
    #     kafka-node-03:
    #       ansible_host: 192.168.0.193
    #       kafka_node_id: 3
    #       kafka_node_roles: ['broker', 'controller']

    # JENKINS
    jenkins_nodes:
      vars:
        # @system: VM Ubuntu 22.04
      hosts:
        jenkins-node-01:
          ansible_host: 192.168.0.114
