all:
  vars:
    #ansible_user: zh
    ansible_ssh_private_key_file: ~/.ssh/vm-arch_zh
    ansible_python_interpreter: /usr/bin/python3
    ansible_become_pass: " "
  children:
    #master_nodes:
      #hosts:
        #vm-arch-13:
          #ansible_host: 192.168.0.185
        #vm-arch-08:
          #ansible_host: 192.168.0.178
    #worker_nodes:
      #hosts:
        #vm-arch-09:
          #ansible_host: 192.168.0.179
        #vm-arch-10:
          #ansible_host: 192.168.0.180
    kafka_nodes:
      vars:
        ansible_user: pop_zh
        ansible_ssh_private_key_file: ~/.ssh/vm-pop_zh
        kafka_install_dependencies: true
        ## kafka_replication_factor: 3
        #kafka_offsets_topic_replication_factor: 3 # Фактор репликации для служебных топиков. Должен быть > 1
        #kafka_transaction_state_log_replication_factor: 3
        #kafka_transaction_state_log_min_isr: 2 # Мин. кол-во реплик для подтверждения записи
      hosts:
        #pop_zh-191:
          #ansible_host: 192.168.0.191
          #kafka_node_id: 1
          #kafka_node_roles: ['broker', 'controller']
        #pop_zh-192:
          #ansible_host: 192.168.0.192
          #ansible_ssh_private_key_file: ~/.ssh/vm-pop_zh
          #kafka_node_id: 2
          #kafka_node_roles: ['broker', 'controller']
        #pop_zh-193:
          #ansible_host: 192.168.0.193
          #kafka_node_id: 3
          #kafka_node_roles: ['broker', 'controller']
        pop_zh-195:
          ansible_host: 192.168.0.195
          kafka_node_id: 1
