all:
  vars:
    ansible_user: zh
    ansible_ssh_private_key_file: ~/.ssh/vm-arch_zh
    ansible_python_interpreter: /usr/bin/python3
    ansible_become_pass: " "
  children:
    master_nodes:
      hosts:
        vm-arch-zh-198:
          ansible_host: 192.168.0.198
    # worker_nodes:
    #   hosts:
    # kafka_nodes:
    #   vars:
    #     ansible_user: pop_zh
    #     ansible_ssh_private_key_file: ~/.ssh/vm-pop_zh
    #     kafka_install_dependencies: true
    #     ## kafka_replication_factor: 3
    #     # kafka_offsets_topic_replication_factor: 3 # Фактор репликации для служебных топиков. Должен быть > 1
    #     # kafka_transaction_state_log_replication_factor: 3
    #     # kafka_transaction_state_log_min_isr: 2 # Мин. кол-во реплик для подтверждения записи
    #   hosts:
    #     vm-ubuntu-pop_zh-191:
    #       ansible_host: 192.168.0.191
    #       kafka_node_id: 1
    #       kafka_node_roles: ['broker', 'controller']
    #     vm-ubuntu-pop_zh-192:
    #       ansible_host: 192.168.0.192
    #       kafka_node_id: 2
    #       kafka_node_roles: ['broker', 'controller']
    #     vm-ubuntu-pop_zh-193:
    #       ansible_host: 192.168.0.193
    #       kafka_node_id: 3
    #       kafka_node_roles: ['broker', 'controller']
    jenkins_nodes:
      vars:
        ansible_user: pop_zh
        ansible_ssh_private_key_file: ~/.ssh/vm-pop_zh
      hosts:
        vm-ubuntu-pop_zh-197:
          ansible_host: 192.168.0.197

