---
- name: Install metrics-server components
  become: true
  ansible.builtin.command: "kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml"
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  changed_when: true

- name: Patch metrics-server for kubeadm clusters
  become: true
  ansible.builtin.command: >
    kubectl patch deployment metrics-server -n kube-system --type='json' 
    -p='[{"op": "add", "path": "/spec/template/spec/containers/0/args/-", "value": "--kubelet-insecure-tls"}]'
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  changed_when: true

