---
# Tasks for control-plane node

- name: Initialize the Kubernetes cluster
  become: true
  ansible.builtin.command: "kubeadm init --pod-network-cidr={{ pod_network_cidr }} --upload-certs"
  args:
    creates: /etc/kubernetes/admin.conf
  when: inventory_hostname == groups['master_nodes'][0]

- name: Set up kubeconfig for ansible user
  become: true
  block:
    - name: Create .kube directory
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/.kube"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Copy admin.conf to user's kubeconfig
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: "/home/{{ ansible_user }}/.kube/config"
        remote_src: true
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'
  when: inventory_hostname == groups['master_nodes'][0]

- name: Install CNI plugin (Flannel)
  ansible.builtin.command: "kubectl apply -f {{ cni_plugin_manifest_url }}"
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  when: inventory_hostname == groups['master_nodes'][0]
  changed_when: true

- name: Generate join command
  ansible.builtin.command: kubeadm token create --print-join-command
  register: join_command_raw
  when: inventory_hostname == groups['master_nodes'][0]
  changed_when: true

- name: Store join command for worker nodes
  ansible.builtin.copy:
    content: "{{ join_command_raw.stdout }}"
    dest: /tmp/kubeadm_join_command.sh
    mode: '0755'
  when: inventory_hostname == groups['master_nodes'][0]

- name: (Optional) Remove taint from control-plane node
  ansible.builtin.command: "kubectl taint nodes --all node-role.kubernetes.io/control-plane-"
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  when:
    - inventory_hostname == groups['master_nodes'][0]
    - remove_control_plane_taint | default(true)
  changed_when: true
