---
# tasks file for install_kubernetes

- name: Run cleanup tasks if k8s_cleanup is true
  ansible.builtin.include_tasks: clear-node.yml
  when: k8s_cleanup | default(false) | bool

- name: Gather facts
  ansible.builtin.setup:

- name: Run common installation tasks for all nodes
  ansible.builtin.include_tasks: common.yml

- name: Run control-plane specific tasks
  ansible.builtin.include_tasks: control-plane.yml
  when: inventory_hostname in groups['master_nodes']

- name: Run worker specific tasks
  ansible.builtin.include_tasks: worker.yml
  when: inventory_hostname in groups['worker_nodes']
