---
# main tasks file for k8s_install

- name: Run cleanup if requested
  ansible.builtin.include_tasks: cleanup.yml
  when: k8s_cleanup | default(false)

- name: Gather facts
  ansible.builtin.setup:

- name: Run common pre-installation tasks
  ansible.builtin.include_tasks: pre-install.yml

- name: Run control-plane specific tasks
  ansible.builtin.include_tasks: control-plane.yml
  when: inventory_hostname in groups['master_nodes']

- name: Run worker specific tasks
  ansible.builtin.include_tasks: workers.yml
  when: inventory_hostname in groups['worker_nodes']
