---
- name: Stop services
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
  loop:
    - kubelet
    - containerd
  ignore_errors: true

- name: Delete CNI network interfaces
  become: true
  ansible.builtin.command: "ip link delete {{ item }}"
  loop:
    - cni0
    - flannel.1
  register: delete_result
  changed_when: delete_result.rc == 0
  failed_when:
    - delete_result.rc != 0
    - "'Cannot find device' not in delete_result.stderr"

- name: Remove CNI configuration files
  become: true
  ansible.builtin.file:
    path: /etc/cni/net.d
    state: absent
