---
# Tasks for worker nodes

- name: Reset worker node to a clean state
  become: true
  ansible.builtin.command: kubeadm reset -f
  ignore_errors: true

- name: Fetch join command from master
  ansible.builtin.slurp:
    src: /tmp/kubeadm_join_command.sh
  register: join_command_slurp
  delegate_to: "{{ groups['master_nodes'][0] }}"

- name: Join the worker node to the cluster
  become: true
  ansible.builtin.command: "{{ join_command_slurp.content | b64decode | trim }}"