# ┌───────────────────────────────────────────────────────────────────────────┐
# │ @category   Ansible Group Variables                                       │
# │ @scope      Переменные для группы [jenkins_nodes] в окружении [dev]       │
# │ @purpose    Переопределение дефолтных значений из роли 'install_jenkins'  │
# └───────────────────────────────────────────────────────────────────────────┘
---

# -----------------------------------------------------------------------------
# @section     Основные параметры Jenkins
# @description Эти переменные определяют базовое поведение и доступ к Jenkins.
#              `jenkins_admin_password` КРАЙНЕ рекомендуется менять для production.
# -----------------------------------------------------------------------------
jenkins_admin_password: "admin"
jenkins_force_clean_install: true
jenkins_url: ""  # Оставьте пустым для авто-определения, или укажите FQDN, например http://jenkins.mycompany.com
jenkins_tunnel: "" # Оставьте пустым для авто-определения

# -----------------------------------------------------------------------------
# @section     Управление ресурсами
# @description Настройки лимитов и запросов ресурсов для контейнера Jenkins.
# -----------------------------------------------------------------------------
jenkins_resource_limits_enabled: true
jenkins_cpu_limit: '1.0'
jenkins_mem_limit: '2g'
jenkins_mem_reservation: '1g'

# -----------------------------------------------------------------------------
# @section     Настройки кэширования для Kubernetes агентов
# @description Параметры для PersistentVolumeClaim, используемого для кэша.
# -----------------------------------------------------------------------------
# Включаем создание и PV (hostPath), и PVC для простоты развертывания в dev.
jenkins_k8s_create_pv: true
jenkins_k8s_create_pvc: true

# Можно также переопределить другие параметры, например, режим доступа для NFS
# jenkins_k8s_pvc_access_modes: [ReadWriteMany]
# jenkins_k8s_pvc_storage_class: "nfs-client"


# -----------------------------------------------------------------------------
# @section     Дополнительные плагины
# @description Список плагинов, которые будут установлены вдобавок к основным.
# -----------------------------------------------------------------------------
# jenkins_plugins_extra:
#   - { name: "blueocean", version: "1.25.3" }

