# ┌───────────────────────────────────────────────────────────────────────────┐
# │ @category   Ansible Group Variables                                       │
# │ @scope      Переменные для группы [jenkins_nodes] в окружении [dev]       │
# │ @purpose    Переопределение дефолтных значений из роли 'install_jenkins'  │
# └───────────────────────────────────────────────────────────────────────────┘
---

jenkins_admin_password: admin

