---
- name: Install and configure Jenkins Controller
  hosts: jenkins_nodes
  become: true

  pre_tasks:
    - name: "Wipe Jenkins home contents to ensure clean install"
      ansible.builtin.shell: "rm -rf /var/jenkins_home/* /var/jenkins_home/.*"
      args:
        warn: false
      when: jenkins_force_clean_install | bool

  roles:
    - role: install_jenkins
