all:
  vars:
    ansible_user: y.paitash
    ansible_ssh_private_key_file: ~/.ssh/active-bank
    ansible_python_interpreter: /usr/bin/python3
  children:
    #master_nodes:
      #hosts:
    #worker_nodes:
      #hosts:
    kafka_nodes:
      vars:
        kafka_install_dependencies: true
      hosts: 
        active-bank-node2:
          ansible_host: 172.17.1.22
          kafka_node_id: 1
          kafka_node_roles: ['broker', 'controller']
