all:
  vars:
    ansible_user: y.paitash
    ansible_ssh_private_key_file: ~/.ssh/active-bank
    ansible_python_interpreter: /usr/bin/python3
  children:
    #master_nodes:
      #hosts:
    #worker_nodes:
      #hosts:
    single_nodes:
      hosts: 
        active-bank-node1:
          ansible_host: 172.17.1.25
        active-bank-node2:
          ansible_host: 172.17.1.22

