---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-agent-cache-pv
  namespace: jenkins
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/jenkins-cache" # Директория, которую мы создали на Шаге 1
  persistentVolumeReclaimPolicy: Retain
