---
# infrastructure/ansible/roles/install_jenkins_controller/handlers/main.yml

- name: restart jenkins
  community.docker.docker_compose_v2:
    project_src: "{{ jenkins_home_on_host }}"
    project_name: "{{ jenkins_container_name }}"
    state: present
