galaxy_info:
  author: Gemini
  description: A simplified role to install a Kubernetes cluster on Arch Linux.
  license: Apache-2.0
  min_ansible_version: "2.9"
  platforms:
    - name: ArchLinux
      versions:
        - all
dependencies: []
