---
# handlers file for k8s_install
- name: Restart containerd
  become: true
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    daemon_reload: yes

- name: Restart kubelet
  become: true
  ansible.builtin.systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes
